import type { MarketResult, RegulatoryAlert, ForecastPoint } from '@/types'

// ─── Mock results for HS 151590 (Huile d'argan) ─────────────────────────────

export const MOCK_RESULTS: MarketResult[] = [
  {
    rank: 1,
    country: { code: 'FRA', name: 'France', flag: '🇫🇷' },
    score_final: 100,
    score_weighted: 94.2,
    score_xgboost: 89.3,
    dimensions: [
      { nom: 'Potentiel de marché',    score: 88, poids: 0.28, contribution: 24.6, detail: { 'Volume importé': '18.5M USD/an', 'Croissance': '+8.2%/an', 'Prix moyen': '29.8 USD/kg' }, interpretation: 'Grand marché de 18.5M USD/an, croissance modérée.' },
      { nom: 'Accord commercial',      score: 100, poids: 0.22, contribution: 22.0, detail: { "Type d'accord": "Accord d'association UE", 'Droits de douane': '0.0%' }, interpretation: "Accord d'association UE — entrée en franchise de droits." },
      { nom: 'Facilité des affaires',  score: 80, poids: 0.18, contribution: 14.4, detail: { 'Ease of Business (WB)': '76.8/100', 'État de droit': '86.0/100', 'Qualité réglementaire': '87.3/100' }, interpretation: 'Bon environnement des affaires.' },
      { nom: 'Stabilité & risque pays',score: 72, poids: 0.12, contribution: 8.6,  detail: { 'Stabilité politique': '55.2/100', 'Risque global': '70.6/100' }, interpretation: 'Pays stable, risque pays faible.' },
      { nom: 'Diaspora marocaine',     score: 100, poids: 0.10, contribution: 10.0, detail: { 'Population MRE': '1,200,000', 'Transferts/an': '2,100M USD' }, interpretation: 'Très forte communauté MRE.' },
      { nom: 'Logistique & transport', score: 92, poids: 0.10, contribution: 9.2,  detail: { 'Distance Casablanca': '2,100 km', 'LPI (World Bank)': '3.84/5', 'Coût conteneur': '1,200 USD' }, interpretation: 'Excellente accessibilité, délais courts.' },
    ],
    shap_values: { 'Diaspora MRE': 12.4, 'Accord commercial': 11.8, 'Volume importé': 8.2, 'Distance logistique': 6.1, 'Droits de douane': 5.9, 'Croissance des imports': 4.3 },
    top_atouts: ["Accord d'association UE — entrée en franchise de droits.", 'Très forte communauté MRE (1,200,000 personnes).', 'Excellente accessibilité (2,100 km, LPI 3.8/5).'],
    top_risques: [],
    accord_info: { accord: "Accord d'association UE", droits: 0, type: 'ALE' },
    logistique: { distance_km: 2100, lpi: 3.84, cout_conteneur: 1200 },
    forecast: { cagr_prevu: 9.1, valeur_2026: 24.8, tendance: 'haussse' },
  },
  {
    rank: 2,
    country: { code: 'USA', name: 'États-Unis', flag: '🇺🇸' },
    score_final: 95,
    score_weighted: 90.1,
    score_xgboost: 86.7,
    dimensions: [
      { nom: 'Potentiel de marché',    score: 100, poids: 0.28, contribution: 28.0, detail: { 'Volume importé': '24.2M USD/an', 'Croissance': '+15.4%/an', 'Prix moyen': '31.0 USD/kg' }, interpretation: 'Grand marché de 24.2M USD/an, croissance forte.' },
      { nom: 'Accord commercial',      score: 100, poids: 0.22, contribution: 22.0, detail: { "Type d'accord": 'Accord de libre-échange', 'Droits de douane': '0.0%' }, interpretation: 'ALE — entrée en franchise de droits.' },
      { nom: 'Facilité des affaires',  score: 86, poids: 0.18, contribution: 15.5, detail: { 'Ease of Business (WB)': '84.0/100', 'État de droit': '90.1/100', 'Qualité réglementaire': '89.9/100' }, interpretation: 'Très bon environnement des affaires.' },
      { nom: 'Stabilité & risque pays',score: 55, poids: 0.12, contribution: 6.6,  detail: { 'Stabilité politique': '48.6/100', 'Risque global': '69.4/100' }, interpretation: 'Stabilité moyenne, surveiller.' },
      { nom: 'Diaspora marocaine',     score: 62, poids: 0.10, contribution: 6.2,  detail: { 'Population MRE': '100,000', 'Transferts/an': '420M USD' }, interpretation: 'Communauté MRE significative.' },
      { nom: 'Logistique & transport', score: 52, poids: 0.10, contribution: 5.2,  detail: { 'Distance Casablanca': '7,500 km', 'LPI (World Bank)': '3.89/5', 'Coût conteneur': '2,800 USD' }, interpretation: 'Distance importante, prévoir délais élevés.' },
    ],
    shap_values: { 'Volume importé': 14.2, 'Accord commercial': 11.8, 'Croissance des imports': 9.6, 'Ease of Business': 7.1, 'Distance logistique': -4.2, 'Risque pays global': -2.8 },
    top_atouts: ['Grand marché de 24.2M USD/an, croissance forte (+15.4%/an).', 'ALE — entrée en franchise de droits.', 'Très bon environnement des affaires.'],
    top_risques: ['Logistique & transport (52/100) — Distance importante (7,500 km).'],
    accord_info: { accord: 'Accord de libre-échange', droits: 0, type: 'ALE' },
    logistique: { distance_km: 7500, lpi: 3.89, cout_conteneur: 2800 },
    forecast: { cagr_prevu: 14.2, valeur_2026: 32.5, tendance: 'haussse' },
  },
  {
    rank: 3,
    country: { code: 'JPN', name: 'Japon', flag: '🇯🇵' },
    score_final: 82,
    score_weighted: 78.4,
    score_xgboost: 75.2,
    dimensions: [
      { nom: 'Potentiel de marché',    score: 72, poids: 0.28, contribution: 20.2, detail: { 'Volume importé': '7.6M USD/an', 'Croissance': '+22.1%/an', 'Prix moyen': '40.0 USD/kg' }, interpretation: 'Marché moyen de 7.6M USD/an, croissance très forte.' },
      { nom: 'Accord commercial',      score: 62, poids: 0.22, contribution: 13.6, detail: { "Type d'accord": 'Aucun accord préférentiel', 'Droits de douane': '3.2%' }, interpretation: 'Pas d\'accord préférentiel — droits à 3.2%.' },
      { nom: 'Facilité des affaires',  score: 82, poids: 0.18, contribution: 14.8, detail: { 'Ease of Business (WB)': '78.0/100', 'État de droit': '89.4/100', 'Qualité réglementaire': '88.7/100' }, interpretation: 'Bon environnement des affaires.' },
      { nom: 'Stabilité & risque pays',score: 90, poids: 0.12, contribution: 10.8, detail: { 'Stabilité politique': '80.5/100', 'Risque global': '85.0/100' }, interpretation: 'Pays très stable, risque pays très faible.' },
      { nom: 'Diaspora marocaine',     score: 5,  poids: 0.10, contribution: 0.5,  detail: { 'Population MRE': '2,000', 'Transferts/an': '8M USD' }, interpretation: 'Peu de diaspora marocaine.' },
      { nom: 'Logistique & transport', score: 22, poids: 0.10, contribution: 2.2,  detail: { 'Distance Casablanca': '14,000 km', 'LPI (World Bank)': '4.03/5', 'Coût conteneur': '4,500 USD' }, interpretation: 'Distance très importante, coûts élevés.' },
    ],
    shap_values: { 'Stabilité politique': 9.8, 'Croissance des imports': 9.2, 'Volume importé': 6.1, 'LPI logistique': 4.5, 'Distance logistique': -8.2, 'Diaspora MRE': -5.4 },
    top_atouts: ['Pays très stable, risque pays très faible.', 'Marché moyen de 7.6M USD/an, croissance très forte (+22.1%/an).', 'Meilleur prix moyen : 40.0 USD/kg.'],
    top_risques: ['Logistique & transport (22/100) — Distance très importante (14,000 km).', 'Diaspora marocaine (5/100) — Peu de diaspora.'],
    accord_info: { accord: 'Aucun accord préférentiel', droits: 3.2, type: 'NPF' },
    logistique: { distance_km: 14000, lpi: 4.03, cout_conteneur: 4500 },
    forecast: { cagr_prevu: 20.5, valeur_2026: 11.2, tendance: 'haussse' },
  },
  {
    rank: 4,
    country: { code: 'SAU', name: 'Arabie Saoudite', flag: '🇸🇦' },
    score_final: 74,
    score_weighted: 70.2,
    score_xgboost: 68.5,
    dimensions: [
      { nom: 'Potentiel de marché',    score: 68, poids: 0.28, contribution: 19.0, detail: { 'Volume importé': '5.2M USD/an', 'Croissance': '+9.7%/an', 'Prix moyen': '28.9 USD/kg' }, interpretation: 'Marché moyen de 5.2M USD/an.' },
      { nom: 'Accord commercial',      score: 100, poids: 0.22, contribution: 22.0, detail: { "Type d'accord": 'Zone arabe libre-échange GAFTA', 'Droits de douane': '0.0%' }, interpretation: 'GAFTA — entrée en franchise de droits.' },
      { nom: 'Facilité des affaires',  score: 65, poids: 0.18, contribution: 11.7, detail: { 'Ease of Business (WB)': '71.6/100', 'État de droit': '55.2/100', 'Qualité réglementaire': '57.0/100' }, interpretation: 'Environnement des affaires moyen.' },
      { nom: 'Stabilité & risque pays',score: 40, poids: 0.12, contribution: 4.8,  detail: { 'Stabilité politique': '32.5/100', 'Risque global': '43.9/100' }, interpretation: 'Risque pays élevé, sécuriser les paiements.' },
      { nom: 'Diaspora marocaine',     score: 35, poids: 0.10, contribution: 3.5,  detail: { 'Population MRE': '50,000', 'Transferts/an': '180M USD' }, interpretation: 'Petite communauté MRE.' },
      { nom: 'Logistique & transport', score: 45, poids: 0.10, contribution: 4.5,  detail: { 'Distance Casablanca': '6,500 km', 'LPI (World Bank)': '3.16/5', 'Coût conteneur': '2,200 USD' }, interpretation: 'Bonne accessibilité.' },
    ],
    shap_values: { 'Accord commercial': 11.8, 'Volume importé': 5.4, 'Croissance des imports': 4.2, 'Risque pays global': -6.8, 'État de droit': -5.1, 'Distance logistique': -3.2 },
    top_atouts: ['GAFTA — entrée en franchise de droits.', 'Marché de 5.2M USD/an, croissance modérée (+9.7%/an).'],
    top_risques: ['Stabilité & risque pays (40/100) — Risque pays élevé, lettre de crédit recommandée.'],
    accord_info: { accord: 'Zone arabe libre-échange GAFTA', droits: 0, type: 'ALE' },
    logistique: { distance_km: 6500, lpi: 3.16, cout_conteneur: 2200 },
    forecast: { cagr_prevu: 11.3, valeur_2026: 7.8, tendance: 'haussse' },
  },
  {
    rank: 5,
    country: { code: 'CAN', name: 'Canada', flag: '🇨🇦' },
    score_final: 65,
    score_weighted: 61.8,
    score_xgboost: 59.4,
    dimensions: [
      { nom: 'Potentiel de marché',    score: 62, poids: 0.28, contribution: 17.4, detail: { 'Volume importé': '6.4M USD/an', 'Croissance': '+11.3%/an', 'Prix moyen': '30.5 USD/kg' }, interpretation: 'Marché de 6.4M USD/an, bonne croissance.' },
      { nom: 'Accord commercial',      score: 28, poids: 0.22, contribution: 6.2,  detail: { "Type d'accord": 'Aucun accord préférentiel', 'Droits de douane': '6.5%' }, interpretation: 'Pas d\'accord préférentiel — droits à 6.5%.' },
      { nom: 'Facilité des affaires',  score: 88, poids: 0.18, contribution: 15.8, detail: { 'Ease of Business (WB)': '79.6/100', 'État de droit': '93.8/100', 'Qualité réglementaire': '94.5/100' }, interpretation: 'Très bon environnement des affaires.' },
      { nom: 'Stabilité & risque pays',score: 92, poids: 0.12, contribution: 11.0, detail: { 'Stabilité politique': '80.2/100', 'Risque global': '87.0/100' }, interpretation: 'Pays très stable.' },
      { nom: 'Diaspora marocaine',     score: 52, poids: 0.10, contribution: 5.2,  detail: { 'Population MRE': '80,000', 'Transferts/an': '310M USD' }, interpretation: 'Communauté MRE significative.' },
      { nom: 'Logistique & transport', score: 40, poids: 0.10, contribution: 4.0,  detail: { 'Distance Casablanca': '8,200 km', 'LPI (World Bank)': '3.73/5', 'Coût conteneur': '3,100 USD' }, interpretation: 'Distance importante, prévoir délais.' },
    ],
    shap_values: { 'Facilité des affaires': 8.4, 'Stabilité politique': 7.9, 'Croissance des imports': 6.2, 'Droits de douane': -7.8, 'Distance logistique': -5.4, 'Coût conteneur': -3.1 },
    top_atouts: ['Très bon environnement des affaires.', 'Pays très stable, risque pays très faible.'],
    top_risques: ['Accord commercial (28/100) — Pas d\'accord préférentiel, droits à 6.5%.', 'Logistique & transport (40/100) — Distance importante (8,200 km).'],
    accord_info: { accord: 'Aucun accord préférentiel', droits: 6.5, type: 'NPF' },
    logistique: { distance_km: 8200, lpi: 3.73, cout_conteneur: 3100 },
    forecast: { cagr_prevu: 12.8, valeur_2026: 9.1, tendance: 'haussse' },
  },
]

// ─── Mock regulatory alerts ──────────────────────────────────────────────────

export const MOCK_ALERTS: RegulatoryAlert[] = [
  {
    id: 'SAU-SFDA-HALAL',
    titre: 'Certification Halal obligatoire — SFDA Arabie Saoudite',
    niveau: 'CRITIQUE',
    source: 'SFDA',
    pays: 'SAU',
    pays_nom: 'Arabie Saoudite',
    date: '2023-01-01',
    resume: "L'Arabie Saoudite exige une certification Halal reconnue par la SFDA pour tous les produits alimentaires importés. La certification doit être émise par un organisme accrédité par l'OIC.",
    action: "Obtenir la certification Halal auprès d'un organisme reconnu par l'IOAS (ex: ONSSA Maroc). Renouvellement annuel.",
    url: 'https://www.sfda.gov.sa/en',
    score_impact: 95,
    llm_enhanced: false,
  },
  {
    id: 'EU-2024-DEFORESTATION',
    titre: 'Règlement UE anti-déforestation (EUDR)',
    niveau: 'CRITIQUE',
    source: 'EUR-Lex',
    pays: 'EU',
    pays_nom: 'Union Européenne',
    date: '2024-01-01',
    resume: 'Tout produit lié à des terres déboisées après 2020 est interdit à l\'importation dans l\'UE. Obligation de traçabilité géographique complète.',
    action: 'Préparer la documentation de traçabilité. Géolocalisation des parcelles de production obligatoire.',
    url: 'https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32023R1115',
    score_impact: 90,
    delai_jours: 60,
    llm_enhanced: true,
  },
  {
    id: 'USA-FDA-FSMA',
    titre: 'FSMA — Food Safety Modernization Act (règles import)',
    niveau: 'ATTENTION',
    source: 'FDA',
    pays: 'USA',
    pays_nom: 'États-Unis',
    date: '2023-01-01',
    resume: 'La FDA exige que les importateurs américains vérifient que leurs fournisseurs étrangers appliquent des mesures préventives conformes au FSMA.',
    action: "S'enregistrer sur le portail FDA (gratuit). Préparer le plan HACCP conforme FSMA.",
    url: 'https://www.fda.gov/food/food-safety-modernization-act-fsma',
    score_impact: 75,
    llm_enhanced: true,
  },
  {
    id: 'EU-2026-ETIQUETAGE',
    titre: 'Étiquetage empreinte carbone sur huiles alimentaires',
    niveau: 'ATTENTION',
    source: 'EUR-Lex',
    pays: 'EU',
    pays_nom: 'Union Européenne',
    date: '2026-01-01',
    resume: "À partir de janvier 2026, l'UE exige l'affichage de l'empreinte carbone sur les emballages des huiles alimentaires importées.",
    action: "Réaliser un bilan carbone du produit. Prévoir la refonte des étiquettes avant fin 2025.",
    url: 'https://ec.europa.eu/food/safety/labelling_nutrition',
    score_impact: 70,
    delai_jours: 180,
    llm_enhanced: false,
  },
  {
    id: 'EU-RASFF-RESIDUS',
    titre: 'Limites maximales de résidus (LMR) pesticides',
    niveau: 'INFO',
    source: 'RASFF',
    pays: 'EU',
    pays_nom: 'Union Européenne',
    date: '2023-06-01',
    resume: "L'EFSA a révisé les LMR pour 50 substances actives. Durcissement notable pour les produits frais méditerranéens.",
    action: 'Mettre à jour les protocoles de traitement phytosanitaire. Tester avant expédition.',
    url: 'https://www.efsa.europa.eu/fr/topics/topic/pesticides',
    score_impact: 55,
    llm_enhanced: false,
  },
  {
    id: 'CAN-CFIA-ORGANIC',
    titre: 'Certification biologique Canada — équivalence Maroc',
    niveau: 'INFO',
    source: 'CFIA Canada',
    pays: 'CAN',
    pays_nom: 'Canada',
    date: '2023-01-01',
    resume: 'Le Canada reconnaît les certifications bio marocaines (ONSSA) comme équivalentes à la norme biologique canadienne.',
    action: 'Conserver et joindre le certificat ONSSA. Mentionner l\'accord d\'équivalence sur la documentation douanière.',
    url: 'https://inspection.canada.ca/organic-products/',
    score_impact: 15,
    llm_enhanced: false,
  },
]

// ─── Mock forecast data (France, HS 151590) ──────────────────────────────────

export const MOCK_FORECAST: import('@/types').ForecastPoint[] = [
  { ds: '2015-01-01', yhat: 8200000,  yhat_lower: 7800000,  yhat_upper: 8600000,  y: 8400000  },
  { ds: '2016-01-01', yhat: 9100000,  yhat_lower: 8600000,  yhat_upper: 9600000,  y: 9300000  },
  { ds: '2017-01-01', yhat: 10500000, yhat_lower: 9900000,  yhat_upper: 11100000, y: 10200000 },
  { ds: '2018-01-01', yhat: 12200000, yhat_lower: 11500000, yhat_upper: 12900000, y: 12700000 },
  { ds: '2019-01-01', yhat: 14100000, yhat_lower: 13300000, yhat_upper: 14900000, y: 13900000 },
  { ds: '2020-01-01', yhat: 14800000, yhat_lower: 13900000, yhat_upper: 15700000, y: 14200000 },
  { ds: '2021-01-01', yhat: 16200000, yhat_lower: 15200000, yhat_upper: 17200000, y: 16800000 },
  { ds: '2022-01-01', yhat: 17800000, yhat_lower: 16700000, yhat_upper: 18900000, y: 18500000 },
  { ds: '2023-01-01', yhat: 20100000, yhat_lower: 18800000, yhat_upper: 21400000 },
  { ds: '2024-01-01', yhat: 21800000, yhat_lower: 20200000, yhat_upper: 23400000 },
  { ds: '2025-01-01', yhat: 23600000, yhat_lower: 21700000, yhat_upper: 25500000 },
  { ds: '2026-01-01', yhat: 24800000, yhat_lower: 22500000, yhat_upper: 27100000 },
]
